apiVersion: v1
kind: Secret
metadata:
  name: gitlab-user-pass
  annotations:
    tekton.dev/git-0: http://10.2.1.45:30011
    #tekton.dev/git-1: https://gitlab.com
    #tekton.dev/docker-0: https://gcr.io
type: kubernetes.io/basic-auth
stringData:
  username: root
  password: admin321