apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-to-k8s
spec:
  inputs:
    resources:
      - name: source
        type: git
  params:
    - name: pathToYamlFile
      description: The path to the yaml file to deploy within the git source
      default: deployment.yaml
    - name: image-tag
      description: Tag to apply to the built image

  steps:
    # 修改deployment.yml的imagetag
    - name: update-yaml
      image: alpine
      command: ["sed"]
      args:
        - "-i"
        - "-e"
        - "s;imagetag;$(params.imagetag);g"
        - "source/$(inputs.params.pathToYamlFile)"  
    
    - name: run-kubectl
      image: lachlanevenson/k8s-kubectl:latest
      imagePullPolicy: IfNotPresent
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "source/$(inputs.params.pathToYamlFile)"