apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-to-k8s
spec:
  params:
    - name: pathToYamlFile
      description: The path to the yaml file to deploy within the git source
    - name: image-tag
      description: Tag to apply to the built image
  workspaces:
    - name: source
  steps:
    # 修改deployment.yml的imagetag
    - name: update-yaml
      image: alpine
      command: ["sed"]
      args:
        - "-i"
        - "-e"
        - "s;imagetag;$(params.image-tag);g"
        - "$(workspaces.source.path)/$(inputs.params.pathToYamlFile)"  
    
    - name: run-kubectl
      image: lachlanevenson/k8s-kubectl:latest
      imagePullPolicy: IfNotPresent
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "$(workspaces.source.path)/$(inputs.params.pathToYamlFile)"
