# 关联triggertemplate和triggerbinding
apiVersion: triggers.tekton.dev/v1alpha1 
kind: EventListener
metadata:
  name: trigger-test-eventlistener
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: trigger
      interceptors:
          - gitlab:
              # 配置gitlab的信息和Token的key
              secretRef:
                secretName: gitlab-token 
                secretKey: secretToken 
              eventTypes:
                - Push Hook
      bindings:
        - ref: trigger-test-triggerbinding
      template:
        ref: trigger-test-triggertemplate
