# 关联triggertemplate和triggerbinding
apiVersion: triggers.tekton.dev/v1alpha1 
kind: EventListener
metadata:
  name: trigger-release-eventlistener
  #annotations:
     #service.beta.kubernetes.io/alibaba-cloud-loadbalancer-force-override-listeners: "true"
     #service.beta.kubernetes.io/alibaba-cloud-loadbalancer-id: lb-xxxxxxxxxxxxx
     #service.beta.kubernetes.io/alibaba-cloud-loadbalancer-protocol-port: "https:443"
spec:
  resources:
    kubernetesResource:
      serviceType: LoadBalancer
      spec:
         template:
            metadata:
              annotations:
                 service.beta.kubernetes.io/alibaba-cloud-loadbalancer-id: lb-xxxxxxxxxxxxx
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: trigger
      interceptors:
          - gitlab:
              # 配置gitlab的信息和Token的key
              secretRef:
                secretName: gitlab-token 
                secretKey: secretToken 
              eventTypes:
                - Push Hook
      bindings:
        - ref: trigger-release-triggerbinding
      template:
        ref: trigger-release-triggertemplate
