apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: trigger-release-triggerbinding
spec:
  # Gitlab Webhook可参考文档：https://docs.gitlab.com/ee/user/project/integrations/webhook_events.html#push-events
  params:
    - name: gitrevision
      value: $(body.after)
    - name: namespace
      value: default
    - name: gitrepositoryurl
      value: $(body.project.git_http_url)
    - name: projectname
      value: $(body.project.name)
