apiVersion: v1
kind: Secret
metadata:
  name: gitlab-user-pass
  annotations:
    # tekton.dev/git-0: http://10.2.1.45:30011
    tekton.dev/git-0: http://192.168.203.129:30011
    #tekton.dev/docker-0: https://gcr.io
type: kubernetes.io/basic-auth
stringData:
  username: root
  password: admin321 

# 创建docker auth
# https://tekton.dev/docs/pipelines/auth/#configuring-docker-authentication-for-docker
# kubectl create secret generic regcred --from-file=.dockerconfigjson=/data/kaniko/.docker/config.json --type=kubernetes.io/dockerconfigjson
