apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: fetch-build-deploy-run
spec:
  # 需要执行的pipeline
  pipelineRef:
    name: fetch-build-deploy
  
  # 使用resourceSpec直接在pipelinerun创建piplineResource
  resources:
    - name: git-repo
      resourceSpec:
        type: git
        params:
          - name: revision
            value: main
          - name: url
            value:  http://gitlab4dev.5ypy.com/luyujiang/oreo-console-client.git

  # 传入pipeline需要的参数
  params:
    - name: image-url
      value: harbor.996a.com:8443/website/
    - name: image-tag
      value: latest
    - name: image-appname
      value: console-client
    - name: pathToYamlFile
      value: deployment.yaml

  # workspaces用于Task间的数据传递
  # 官方推荐pv/pvc方式,而不推荐pipeResource方式（原因是"https://tekton.dev/docs/pipelines/resources/#why-aren-t-pipelineresources-in-beta"）
  # 其他参考资料：
  #   https://github.com/tektoncd/pipeline/pull/2326

  # workspaces:
  #   - name: myworkspace
  #     persistentVolumeClaim:
  #       claimName: mypvc
  #     subPath: my-subdir

  # workspaces:
  #   - name: shared-data
  #     volumeClaimTemplate:
  #       spec:
  #         accessModes:
  #         - ReadWriteOnce
  #         resources:
  #           requests:
  #             storage: 1Gi

  workspaces:
    - name: docker-config
      secret:
        secretName: docker-config
  # sa
  serviceAccountName: tekton-build
