apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: fetch-build-deploy-run
spec:
  # 需要执行的pipeline
  pipelineRef:
    name: fetch-build-deploy
  
  # 传入pipeline需要的参数
  params:
    - name: git-revision
      value: main
    - name: git-url
      value: http://gitlab4dev.5ypy.com/luyujiang/oreo-console-client.git  
    - name: image-url
      value: harbor.996a.com:8443/website/
    - name: image-tag
      value: latest
    - name: image-appname
      value: console-client
    - name: pathToYamlFile
      value: deployment.yaml

  # workspaces用于Task间的数据传递（即pods间多个container共享数据问题）
  # 官方推荐pv/pvc方式,而不推荐pipeResource方式（原因是"https://tekton.dev/docs/pipelines/resources/#why-aren-t-pipelineresources-in-beta"）
  # 其他参考资料：
  #   https://github.com/tektoncd/pipeline/pull/2326

  # workspaces:
  #   - name: myworkspace
  #     persistentVolumeClaim:
  #       claimName: mypvc
  #     subPath: my-subdir

  workspaces:
    - name: shared-data
      # volumeClaimTemplate相当于kind:PersistentVolumeClaim. 是一份pvc的申请.
      volumeClaimTemplate:
        metadata:
          name: tekton-pvc
        spec:
          accessModes: ["ReadWriteMany"]
          resources:
            requests:
              storage: 1Gi
    - name: docker-config
      secret:
        secretName: regcred
  # sa
  serviceAccountName: tekton-build
